UPDATE blog_posts
SET content_json = '[{"id":"paragraph-mony0x4a-v5ng9rqp","type":"paragraph","props":{"text":"手機又留有好幾則未回的訊息"}},{"id":"paragraph-mony0x4a-smfohdtf","type":"paragraph","props":{"text":"統編忘記檢查、新窗口還沒連繫、錯誤訊息還沒說明、新的會議還沒約…."}},{"id":"paragraph-mony0x4a-qrxo55k1","type":"paragraph","props":{"text":"好想要無視阿!!!"}},{"id":"paragraph-mony0x4a-7i53ivez","type":"paragraph","props":{"text":"每個提問都有可能是隱藏的缺失，一隻隻箭在朝我射來的路上，我還要打開來被刺成刺蝟嗎?"}},{"id":"paragraph-mony0x4a-p80mpvx8","type":"paragraph","props":{"text":"說我不愛回訊息，但其實我話超多的，根本不怕跟別人溝通。"}},{"id":"paragraph-mony0x4a-mykt9fcy","type":"paragraph","props":{"text":"所謂的不回，是物理上的無視與心理上的不適。"}},{"id":"paragraph-mony0x4a-39cs5ab0","type":"paragraph","props":{"text":"無視、無謂、無法"}},{"id":"paragraph-mony0x4a-jz8yzqjc","type":"paragraph","props":{"text":"慢慢將他放到過期，然後就…"}},{"id":"paragraph-mony0x4a-uqbxt4tb","type":"paragraph","props":{"text":"“哎呀 我忘記了”"}},{"id":"paragraph-mony0x4a-v9tsd1t7","type":"paragraph","props":{"text":"但怎麼可能忘記呢? 最後還是從小本本上被更多代辦事項壓到最底下而已"}},{"id":"paragraph-mony0x4a-pgd7f29k","type":"paragraph","props":{"text":"緊急的狀態等級已經到極限了，驚嘆號再多不夠分類，或者說再多也無法鞭策我進行下一步動作"}},{"id":"paragraph-mony0x4a-kdife3k3","type":"paragraph","props":{"text":"事件的重要跟緊急又總是只有第一象限了。"}},{"id":"paragraph-mony0x4a-ceol0zi9","type":"paragraph","props":{"text":"就像現在我還有些東西，要做、要看。但我還是在這裡跟自己發牢騷。"}},{"id":"paragraph-mony0x4a-i6q131tx","type":"paragraph","props":{"text":"訊息真的好煩阿!!"}},{"id":"paragraph-mony0x4a-3vo7wz4x","type":"paragraph","props":{"text":"但我為什麼怎麼不喜歡面對錯誤呢? 我從未立過完美人設，因為我要用迷糊跟不記得來逃避一些既來的控訴。但我依然對於種種指責採取無視政策，逃避，又是我唯一對自己的慢性毒藥。"}}]'
WHERE slug = 'post-mi4f16ip-egcwkp';

UPDATE blog_posts
SET content_json = '[{"id":"paragraph-mony0x4a-vk6wwefe","type":"paragraph","props":{"text":"回顧我的旅行。"}},{"id":"paragraph-mony0x4a-9dsfauk4","type":"paragraph","props":{"text":"很久沒有出國了，而且還是去往美國，一個總在電視上遙望的國度。"}},{"id":"paragraph-mony0x4a-3esvg5ws","type":"paragraph","props":{"text":"只少，到了現場才驚覺，這個世界比想像中的還近。"}},{"id":"paragraph-mony0x4a-14x19wrg","type":"paragraph","props":{"text":"熟悉而陌生的文化、一目目不該習以為常的景色，映照在眼裡，勾起記憶中的片片文化。"}},{"id":"paragraph-mony0x4a-8k3q7594","type":"paragraph","props":{"text":"要從哪裡細數? 從小的”卡通”，偶而瞥見的美劇，廢寢忘食的美式情景喜劇，還有一部部如數家珍的電影。"}},{"id":"paragraph-mony0x4a-sn2pjurq","type":"paragraph","props":{"text":"雖然那時，所謂版權意識只存在片頭的警告中，後續就會被詭異的、跑到鏡頭前的黑影給遮住了。看著所謂先行版、高清版、超清版、韓語無字版等等，可疑的讓人忘記自己在看電影，彷彿縮於一禺的再看一些糟糕的東西。(當然，現在知道那些糟糕並無差異。)"}},{"id":"paragraph-mony0x4a-oc4g4igm","type":"paragraph","props":{"text":"扯遠了，對於美國的追憶我想接下來還有好大的段落可以不斷穿插，拉回來說這次的旅遊預備。必須說，我所投注的心力真的蠻少的，事前幾乎沒有什麼進行行程規劃，唯一出的意見－\"優勝美地\"。過去的成本又高的離譜，要翻山越嶺才有辦法。 以我對於旅程的掌控程度來說，這一次的可以說是”零”。 至於為什麼會造成這樣的怠惰，回顧一下我自己在旅遊的時候，確實，只要是有旅伴的，我幾乎都懶得安排，也不是沒有毛起來當導遊過，但....就感覺蠻累的，而且與其嘗試搜盡資訊來與自己的期待碰撞，我想，我內心有著潛意識告訴自己，那不如不帶預期的去體驗吧！當然，也不否認，就是我懶罷。"}},{"id":"paragraph-mony0x4a-b52hhiji","type":"paragraph","props":{"text":"我這次，真的已經很早就報備父母了，但鄰近時地提及，自然還是帶給他們”驚喜”。但我想，最大的驚喜，還是留給了我的另一個家－教會。"}},{"id":"paragraph-mony0x4a-0b18ay2f","type":"paragraph","props":{"text":"很難忘記，前一周大家緊鑼密鼓的排演，準備盛大的迎來又一次的農會表演。回顧這個活動，我從不認為自己是重要主角，但也確實，再次次的活動中，被慢慢賦予了一些定位，兒主之友、收線特派員、搬運弟兄組等等。這些不起眼卻又實實在在貢獻的角色，尤其看著其他無名肢體的默默付出，一種感動與使命讓我也產生了捨我其誰的錯覺。"}},{"id":"paragraph-mony0x4a-9p8vieo4","type":"paragraph","props":{"text":"我在排定這場旅遊時，我有沒有想到呢 ? 肯定沒有！　但是隨著時間臨近，大概是兩到三個月的時候，我發現怎麼算、好像都沒辦法避開，那復活的節日。天啊，這下到底該怎麼辦？"}},{"id":"paragraph-mony0x4a-f8g2igof","type":"paragraph","props":{"text":"逃避雖然沒用，但是可以騙過自己，看著日子漸漸地近了，手機拿起來滑開了主德哥的訊息位置，但也依然沒有勇氣坦承。＂下一次見面、下一周、回家後就用訊息＂，一次次的拖延，將石頭漸漸推上高峰。走在逃避的路線中，終究會遇上盡頭。而盡頭，是最溫暖、最洞悉人的師母，我想，這就上帝他的仁慈，用最溫柔的鋼索，漸漸嵌入我的皮膚之中。"}},{"id":"paragraph-mony0x4a-hl9s4z58","type":"paragraph","props":{"text":"＂下周也要麻煩您支援兒主囉！，所以請你也要記得來參加早崇拜。＂隨著師母的詢問，顯然這路已經到了盡頭，隱瞞的控訴已經是最高的罪行，我不可能讓更多的謊言建築在我的家中。"}},{"id":"paragraph-mony0x4a-m28enx0c","type":"paragraph","props":{"text":"＂我下周要出去玩＂，我說的很輕描淡寫，而隨著師母笑著問話，才發現這一切案情並不單純，眼前這小子不只是知情未報，甚至逃避的讓人吃驚了！整整快兩周的行程，竟壓到最後一刻才要鬆口。"}},{"id":"paragraph-mony0x4a-it1rjg0m","type":"paragraph","props":{"text":"＂要我幫你跟主德哥說嗎？＂我當時依然故作堅強的說＂不用＂。再被叮嚀著要好好聚會後，我竟帶著微微的舒坦離開，就好像我自己已經努力過了、做了什麼似的。並沒有！"}},{"id":"paragraph-mony0x4a-cd3m9zq1","type":"paragraph","props":{"text":"我還是高估了我自己的堅決，或說低估自己的無能。直到在機場的一通電話，我的罪惡感才爆發。"}}]'
WHERE slug = 'post-mi4alit2-u8dbwy';

UPDATE blog_posts
SET content_json = '[{"id":"paragraph-mony0x4a-wugpos0w","type":"paragraph","props":{"text":"這次把 React Router v7 loader 與 Workers KV 快取重新整理，\n從 Route Manifest 到 Edge 服務端渲染都記錄下來。\n也練習在 DevTools 觀察 WSS streaming 的效能。"}}]'
WHERE slug = 'workers-routing';

UPDATE blog_posts
SET content_json = '[{"id":"paragraph-mony0x4a-dxi8n0t1","type":"paragraph","props":{"text":"將 UI token 與 CSS variables 調校成兩組色盤，\n在深色背景也能維持柔和節奏。\n同步記錄了 Figma plugin 的測試心得。\n以上都是假的 並沒有"}}]'
WHERE slug = 'color-palette';

UPDATE blog_posts
SET content_json = '[{"id":"paragraph-mony0x4a-r138g92b","type":"paragraph","props":{"text":"時間一年一年的過"}},{"id":"paragraph-mony0x4a-j386kgfl","type":"paragraph","props":{"text":"總在努力尋找些什麼、證明自己存在過"}},{"id":"paragraph-mony0x4a-rdwf811h","type":"paragraph","props":{"text":"但又不知道什麼是自己真正想要的、什麼是自己期待遇見的"}},{"id":"paragraph-mony0x4a-hyfdjok6","type":"paragraph","props":{"text":"什麼是自己內心渴望的"}},{"id":"paragraph-mony0x4a-0gld7c8f","type":"paragraph","props":{"text":"這一年 算是演唱會元年"}},{"id":"paragraph-mony0x4a-jyuqr9tv","type":"paragraph","props":{"text":"我用大大小小的演出畫出我生活個隔間"}},{"id":"paragraph-mony0x4a-moaw8zvu","type":"paragraph","props":{"text":"每場的感動不盡相同、想要留下些什麼，才發現過了一年自己還在盲目的刷卡，而少有將生命的長度延續。"}},{"id":"paragraph-mony0x4a-jgznl5ux","type":"paragraph","props":{"text":"接下來是連續三天的演唱會，幸福之餘，難免開始懷疑自己：這是我想要的豐富嗎？我的寂寞與渴望，是否有在一陣陣的歌聲及樂器中滿足？"}},{"id":"paragraph-mony0x4a-q9vqc2tk","type":"paragraph","props":{"text":"真心懷疑……"}},{"id":"paragraph-mony0x4a-h69b6mzd","type":"paragraph","props":{"text":"前面又看了藍色巨星，對於爵士也燃起了一些興趣，但又害怕這所謂的＂興趣＂，也只是一時興起的激情，等到求知慾、熱度退卻，我又回到地面上繼續撰寫內耗般的文章。"}},{"id":"paragraph-mony0x4a-h8did65g","type":"paragraph","props":{"text":"說也沮喪（？　對於自身的自嘲文章下筆如有神助，但是對於一篇篇自己實際期待的旅遊文章、心得文章，其實一丁點也沒有。"}},{"id":"paragraph-mony0x4a-ntfggma1","type":"paragraph","props":{"text":"感覺是腦裡的片片記憶，當落地之時，猶如雪花，其實沒有想像中繽紛、有趣、充滿靈性與豐富的思緒。"}},{"id":"paragraph-mony0x4a-if6z9t4v","type":"paragraph","props":{"text":"只有水而已。"}}]'
WHERE slug = 'post-mi7a9fyv';

UPDATE blog_posts
SET content_json = '[{"id":"paragraph-mony0x4a-2owavrmm","type":"paragraph","props":{"text":"阿阿阿！感覺我的人生總有些時候不小心按到skip"}}]'
WHERE slug = 'post-mi7a5anc';

UPDATE blog_posts
SET content_json = '[{"id":"paragraph-mony0x4a-lzvoq1go","type":"paragraph","props":{"text":"原本在歌曲中聽到一絲絲的議題的信號"}},{"id":"paragraph-mony0x4a-zlswjc39","type":"paragraph","props":{"text":"原來不是隱含的事件"}},{"id":"paragraph-mony0x4a-1wyavie2","type":"paragraph","props":{"text":"還是專屬的語境"}},{"id":"paragraph-mony0x4a-v46w925s","type":"paragraph","props":{"text":"聽著她敘述一段段富含劇情的歌曲"}},{"id":"paragraph-mony0x4a-66efaa7a","type":"paragraph","props":{"text":"聲音裡的故事，切切的從文字當中滲出"}},{"id":"paragraph-mony0x4a-26dzz80l","type":"paragraph","props":{"text":"距離的近 讓這個分享 更像是對著自己告白"}},{"id":"paragraph-mony0x4a-tr7aeehz","type":"paragraph","props":{"text":"讓訴說的對象如此的近 情緒的傳遞有更多細緻的紋理"}},{"id":"paragraph-mony0x4a-x170ism2","type":"paragraph","props":{"text":"感覺我應該最喜歡這樣的演出"}},{"id":"paragraph-mony0x4a-yj063fmz","type":"paragraph","props":{"text":"雖然信誓旦旦說自己是音樂與文字的信徒"}},{"id":"paragraph-mony0x4a-ont1gwzm","type":"paragraph","props":{"text":"但對於情感渲染的期待才是每每參與的初衷與渴望"}},{"id":"paragraph-mony0x4a-789dwveh","type":"paragraph","props":{"text":"但還是想聽正式演出啦"}},{"id":"paragraph-mony0x4a-i2rp9qto","type":"paragraph","props":{"text":"想要跟著感動、跟著擺動、跟著心動"}},{"id":"paragraph-mony0x4a-ls7nxs3x","type":"paragraph","props":{"text":"跟著一切有趣、也有可能總是不懂的悸動"}}]'
WHERE slug = 'post-mid09khl';