// app/routes.ts
import { type RouteConfig, index, route } from "@react-router/dev/routes";


export default [
  index("routes/missing.tsx"),
  route("jock_space", "routes/home.tsx"),
  route("about", "routes/about.tsx"),
  route("blog", "routes/blog/index.tsx"),
  route("blog/:slug", "routes/blog/$slug.tsx"),
  route("changelog", "routes/changelog.tsx"),
  route("admin/login", "routes/admin/login.tsx"),
  route("admin/blog-edit", "routes/admin/blog-edit.tsx"),
  route("admin", "routes/admin/index.tsx"),
  route("api/admin", "routes/api/rng-prompt-admin.tsx"),
  route("api/data", "routes/api/rng-prompt-data.tsx"),
  route("api/output-configs", "routes/api/output-configs.tsx"),
  route("api/rng-prompt/export", "routes/api/rng-prompt-export.tsx"),
  route("api/rng-prompt/import", "routes/api/rng-prompt-import.tsx"),
  route("api/concert-events", "routes/api/concert-events.tsx"),
  route("api/init", "routes/api/spotify/init.tsx"),
  route("api/save", "routes/api/spotify/save.tsx"),
  route("api/session/:userId", "routes/api/spotify/session.$userId.tsx"),
  route("api/spotify/ids", "routes/api/spotify/ids.tsx"),
  route("api/spotify/artists", "routes/api/spotify/artists.tsx"),
  route("api/spotify/preview/:artistId", "routes/api/spotify/preview.$artistId.tsx"),
  route("api/spotify/latest-release/:artistId", "routes/api/spotify/latest-release.$artistId.tsx"),
  route("outerspace", "routes/outerspace/index.tsx"),
  route("outerspace/OuterSpaceSenter", "routes/outerspace/outerspace-center.tsx"),
  route("outerspace/PokeAPIcreatures", "routes/outerspace/pokeapi-creatures.tsx"),
  route("outerspace/Gravity", "routes/outerspace/gravity.tsx"),
  route("gift", "routes/gift/index.tsx"),
  route("gift/host", "routes/gift/host.tsx"),
  route("spotify", "routes/spotify/index.tsx"),
  route("call_spotify", "routes/spotify/callback.tsx"),
  route("vote", "routes/tools/gift-vote.tsx"),
  route("rng_prompt", "routes/tools/rng-prompt.tsx"),
  route("concert_events", "routes/tools/concert-events.tsx"),
] satisfies RouteConfig;
